---
title: "01 Read data and select needed variables"
author: "Miranda Gómez Díaz"
date: "2023-02-03"
output: html_document
---

```{r}
# Read needed packages
library(tidyverse)
library(eeptools)  
```

```{r}
# Read CDI data
# English
Eng_cdi_data <- read_csv("data/BabysNewWords_data_webCDI_EN_2023_04April.csv",
                         guess_max = 1500) #HK note: some columns are being read in as logical when they should be character, added a line to fix this

# French
Fr_cdi_data <- read_csv("data/BabysNewWords_data_webCDI_FR_2023_04April.csv",
                         guess_max = 1500) #HK note: same as above

# Read LEQ data
# LimeSurvey
LS_LEQ_data <- read_csv("data/LimeSurvey_LEQ_data.csv",
                         guess_max = 1500) #HK note: same as above
# Qualtrics
Q_LEQ_data <- read_csv("data/00_Qualtrics_LEQ_checked_long.csv",
                         guess_max = 1500) #%>% #HK note: same as above

# Read date of birth data
DOB_data <- read_csv("data/BNW_date_of_birth.csv") %>%
  slice(1:138)

```
```{r}
# Prepare LEQ data from LimeSurvey to be joined
# Create dataframe with the study ID and all months of age from 1 to 30
LS_age_df <- data.frame(end_age = 1:30)
LS_study_id_df <- LS_LEQ_data %>% distinct(studyid) %>%
  rename(study_id = studyid)

LS_end_age_df <- merge(LS_study_id_df,LS_age_df)

# Remove unnecessary columns from the LEQ dataframe (LimeSurvey)
LS_LEQ_df_columns <- LS_LEQ_data %>% 
  # Keep only relevant variables
  select(babyid:dob, phase, end_age, cumulative_exp_Eng:cumulative_exp_L4) %>%
  # Rename columns so they match CDI dataframes
  rename(subject_id = babyid,
         study_id = studyid) %>%
  # Create rows for each month, instead of each phase, and fill in empty values
  full_join(LS_end_age_df, by = c("study_id", "end_age")) %>%
  group_by(study_id) %>%
  arrange(end_age) %>%
  fill(-c("study_id", "end_age"), .direction = "up") %>%
  filter(end_age >= 16) %>%
  ungroup() %>% 
  # Format study_id to be "S" followed by 3 digits (e.g., S001, S086, S123)
  mutate(study_id = case_when(str_length(study_id) == 3 ~ gsub("^(.{1})(.*)$",
                                                               "\\10\\2",
                                                               study_id),
                              TRUE ~ study_id)) 
  
```

```{r}
# Prepare LEQ data from Qualtrics to be joined
# Create dataframe with the study ID and all months of age from 1 to 30
Q_age_df <- data.frame(end_age = 1:30)
Q_study_id_df <- Q_LEQ_data %>% distinct(study_id)

Q_end_age_df <- merge(Q_study_id_df,Q_age_df)

# Remove unnecessary columns from the LEQ dataframe (Qualtrics)
Q_LEQ_df_columns <- Q_LEQ_data %>%
  # Keep only relevant variables
  select(baby_id, study_id, date_of_birth, situation, end, lang_name, language, cumu_exp) %>%
  # Convert date of birth colum into date (make it compatible with LimeSurvey)
  mutate(date_of_birth = str_replace_all(date_of_birth, "/", "-")) %>%
  mutate(date_of_birth = as.Date(date_of_birth, format = "%Y-%m-%d")) %>% 
  # Rename columns so they match CDI dataframes
  rename(subject_id = baby_id,
         dob = date_of_birth,
         phase = situation,
         end_age = end,
         cumulative_exp = cumu_exp) %>%
  # Create column to be used to pivot cumulative exposure by language
  mutate(lang = case_when(lang_name == "English" ~ "Eng",
                          lang_name == "French" ~ "Fre",
                          language == "l3" ~ "L3",
                          language == "l4" ~ "L4",
                          lang_name != "English" & lang_name != "French" ~ "L3")) %>%
  # Pivot into wider data (one row per baby per phase)
  pivot_wider(id_cols = c(subject_id, study_id, dob, phase, end_age),
              names_from = lang,
              values_from = cumulative_exp,
              names_prefix = "cumulative_exp_") %>%
  full_join(Q_end_age_df, by = c("study_id", "end_age")) %>%
  group_by(study_id) %>%
  arrange(end_age) %>%
  fill(-c("study_id", "end_age"), .direction = "up") %>%
  filter(end_age >= 16) %>%
  ungroup() %>%
  # Remove rows of months after babies withdrew
  filter(!(is.na(phase)))
```

```{r}
# Merge LimeSurvey and Qualtrics LEQ dataframes
LEQ_df_columns <-
  full_join(LS_LEQ_df_columns, Q_LEQ_df_columns) %>% 
  group_by(study_id) %>% 
  filter(end_age == max(end_age)) %>% 
  mutate(lang_status = case_when(cumulative_exp_Fre>.9 ~ "fr_mono",
                                 cumulative_exp_Eng>.9 ~ "eng_mono",
                                 TRUE ~ "bilingual"),
         dominant_lang = case_when(cumulative_exp_Fre>cumulative_exp_Eng ~ "fr_dom",
                                   cumulative_exp_Fre<cumulative_exp_Eng ~ "eng_dom",
                                   cumulative_exp_Fre==cumulative_exp_Eng ~ "balanced",
                                   cumulative_exp_Fre>cumulative_exp_L3 ~ "fr_dom")) %>% #HK note: this is producing one NA value for "dominant_lang' for a kid who is dominant in French but non-dominant in L3... If you want this kid to also be marked as fr_dom, then you can add this line to the cases: cumulative_exp_Fre>cumulative_exp_L3 ~ "fr_dom". I'm also adding a call to ungroup() here so the dataframe is no longer grouped.
  ungroup() %>% 
  select(-c(subject_id, dob))

# Create dataframe with monolinguals (exposure < 10% to English or French) to later remove their CDI data in their second language if they completed it
# English monolinguals
eng_monolingual_df <- LEQ_df_columns %>% 
  filter(lang_status == "eng_mono")

# French monolinguals
fr_monolingual_df <- LEQ_df_columns %>% 
  filter(lang_status == "fr_mono")
```

```{r}
# Format date of birth data
DOB_data <- DOB_data %>% 
  # Get study ID
  separate(local_lab_id, c(NA, "study_id")) %>% 
  # Format study_id to be "S" followed by 3 digits (e.g., S001, S086, S123)
  mutate(study_id = case_when(str_length(study_id) == 3 ~ gsub("^(.{1})(.*)$",
                                                               "\\10\\2",
                                                               study_id),
                              TRUE ~ study_id))
```

```{r}
# Remove unnecessary columns from the CDI dataframes
# English 
Eng_df_columns <- Eng_cdi_data %>% 
  # Keep only relevant variables
  select(subject_id, local_lab_id, completed, last_modified, sex, birth_order, birth_weight_lb, multi_birth_boolean, born_on_due_date:due_date_diff, form_filler, primary_caregiver, mother_yob:caregiver_info, other_languages_boolean:ear_infections_boolean, hearing_loss_boolean, illnesses_boolean, services_boolean, worried_boolean, baa_baa:then, 'Total Produced') %>%
  # Rename Total Produced column
  rename(eng_total_produced = 'Total Produced') %>%
  # Get study ID and month of entry
  separate(local_lab_id, c(NA, "study_id", "n_months")) %>%
  mutate(n_months = as.numeric(str_sub(n_months, start = 6))) %>%
  # Format study_id to be "S" followed by 3 digits (e.g., S001, S086, S123)
  mutate(study_id = case_when(str_length(study_id) == 3 ~ gsub("^(.{1})(.*)$",
                                                               "\\10\\2",
                                                               study_id),
                              TRUE ~ study_id)) %>% 
  # Get date of birth (DOB)
  group_by(study_id) %>%
  full_join(DOB_data, by = c("subject_id", "study_id")) %>%
  relocate(dob, .before = last_modified) %>%
  # Change dataframe values from strings to numeric (1 = produces, 0 = NA)
  mutate_at(vars(baa_baa:then), funs(replace(.,is.na(.), 0))) %>% 
  mutate_at(vars(baa_baa:then), funs(replace(., which(.=="produces"), 1))) %>%
  mutate_at(vars(baa_baa:then), funs(as.numeric)) %>%
  # Remove participants who asked to withdraw
  # filter(!(subject_id == 56355 | subject_id == 56383 | subject_id == 56397 | subject_id == 54992 | subject_id == 56843 | subject_id == 56896 | subject_id == 55788 | subject_id == 56389 | subject_id == 57445)) %>%
  # Remove participants with strange subject_id (testing)
  filter(!(subject_id == 9998 | subject_id == 9999 | subject_id == 99999 | subject_id == 999996 | subject_id == 999998)) %>%
  # Remove the first of double entries in a single month (completed or incomplete)
  group_by(study_id, n_months) %>%
  arrange(last_modified) %>%
  #filter(!(n_months == lead(n_months))) %>% #HK note: this line seems to be removing some rows I think you want to keep (i.e., subject S015 has two entries for month 14, and this code is removing both of those rows, when I think you want to keep the completed one. It was also removing others that didn't have duplicate entries, like S127 month 15. I've updated the code in line 177 and the next line to fix this issue.)
  slice_tail() %>% #HK note: this keeps the bottom-most row for each group and removes the rest. slice_head() does the same, but takes the top-most row.
  #Remove participants with 0 or 1 valid observation
  group_by(study_id) %>%
  mutate(TRUE_months = sum(completed == TRUE)) %>%
  relocate(TRUE_months, .after = study_id) %>%
  ungroup() %>%
  filter(TRUE_months>1) %>%
# Estimate precise age
  mutate(last_modified = as.Date(as.POSIXct(last_modified, 'GMT'))) %>%
  mutate(age = age_calc(dob, last_modified, units = "months")) %>% 
  relocate(age, .after = last_modified) %>% 
  # Remove data from French monolinguals
  filter(!(study_id %in% fr_monolingual_df$study_id)) %>% 
  select(-c(subject_id, dob, last_modified))
  

# French 
Fr_df_columns <- Fr_cdi_data %>%
  # keep only relevant variables
  select(subject_id, local_lab_id, completed, last_modified, sex, birth_order, birth_weight_lb, multi_birth_boolean, born_on_due_date:due_date_diff, form_filler, primary_caregiver, mother_yob:caregiver_info, other_languages_boolean:ear_infections_boolean, hearing_loss_boolean, illnesses_boolean, services_boolean, worried_boolean, aie:si, 'Total Produced') %>%
  # Rename Total Produced column
  rename(fr_total_produced = 'Total Produced') %>%
  # Get study ID and month of entry
  separate(local_lab_id, c(NA, "study_id", "n_months")) %>%
  mutate(n_months = as.numeric(str_sub(n_months, start = 6))) %>%
  # Format study_id to be "S" followed by 3 digits (e.g., S001, S086, S123)
  mutate(study_id = case_when(str_length(study_id) == 3 ~ gsub("^(.{1})(.*)$",
                                                               "\\10\\2",
                                                               study_id),
                              TRUE ~ study_id)) %>% 
  # Get date of birth (DOB)
  group_by(study_id) %>%
  full_join(DOB_data, by = c("subject_id", "study_id")) %>%
  relocate(dob, .before = last_modified) %>%
  # Change dataframe values from strings to numeric (1 = produces, 0 = NA)
  mutate_at(vars(aie:si), funs(replace(.,is.na(.), 0))) %>% 
  mutate_at(vars(aie:si), funs(replace(., which(.=="produces"), 1))) %>%
  mutate_at(vars(aie:si), funs(as.numeric)) %>%
  # Remove participants who asked to withdraw
  # filter(!(subject_id == 56355 | subject_id == 56383 | subject_id == 56397 | subject_id == 54992 | subject_id == 56843 | subject_id == 56896 | subject_id == 55788 | subject_id == 56389 | subject_id == 57445)) %>%
  # Remove participants with strange subject_id (testing)
  filter(!(subject_id == 99998 | subject_id == 999996 | subject_id == 999998 | subject_id == 1000006)) %>%
  # Remove the first of double entries in a single month (completed or incomplete)
  group_by(study_id, n_months) %>%
  arrange(last_modified) %>%
  #filter(!(n_months == lead(n_months))) %>% #HK note: this line seems to be removing some rows I think you want to keep (i.e., subject S015 has two entries for month 14, and this code is removing both of those rows, when I think you want to keep the completed one. It was also removing others that didn't have duplicate entries, like S127 month 15. I've updated the code in the next line to fix this issue.)
  slice_tail() %>% #HK note: this keeps the bottom-most row for each group and removes the rest. slice_head() does the same, but takes the top-most row.
  #Remove participants with 0 or 1 valid observation
  group_by(study_id) %>%
  mutate(TRUE_months = sum(completed == TRUE)) %>%
  relocate(TRUE_months, .after = study_id) %>%
  ungroup() %>%
  filter(TRUE_months>1) %>%
  # Estimate precise age
  mutate(last_modified = as.Date(as.POSIXct(last_modified, 'GMT'))) %>%
  mutate(age = age_calc(dob, last_modified, units = "months")) %>%
  relocate(age, .after = last_modified) %>% 
  # Remove data from English monolinguals
  filter(!(study_id %in% eng_monolingual_df$study_id)) %>% 
  select(-c(subject_id, dob, last_modified))

```

```{r}
# Save dataframes as csv files
write_csv(Eng_df_columns, 'data/01_Eng_columns.csv')
write_csv(Fr_df_columns, 'data/01_Fr_columns.csv')
write_csv(LEQ_df_columns, 'data/01_LEQ_columns.csv')

```

