---
title: "data_dictionary"
author: "Miranda Gómez Díaz"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
# Load packages
library(tidyverse)
library(datadictionary)
library(pointblank)
library(rio)
# library(dplyr)
```

```{r}
################# Datasets used for Script 02 ################# 
```

```{r}
# Data dictionary for 01_LEQ_columns.csv

# Read csv file
LEQ_01_df <- read_csv("data/01_LEQ_columns.csv")

# Create dictionary
LEQ_01_dictionary <- create_informant(LEQ_01_df) %>% 
  info_tabular(
    Description = "Dataset of language exposure data.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>%
  info_columns(
    columns = "phase",
    info = "Number of the current language exposure situation being reported for a participant.") %>%
  info_columns(
    columns = "end_age",
    info = "Participant's age in months at which the current phage ended.") %>%
  info_columns(
    columns = "cumulative_exp_Eng",
    info = "Exposure to English that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>%
  info_columns(
    columns = "cumulative_exp_Fre",
    info = "Exposure to French that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>%
  info_columns(
    columns = "cumulative_exp_L3",
    info = "Exposure to a third language that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>%
  info_columns(
    columns = "cumulative_exp_L4",
    info = "Exposure to a fourth language that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>%
  info_columns(
    columns = "lang_status",
    info = "Specifies if a participant is bilingual, English-monolingual or French-monolingual.") %>%
  info_columns(
    columns = "dominant_lang",
    info = "Specifies a participant's dominant language.") 

LEQ_01_dictionary
```

```{r}
# Data dictionary for 01_Eng_columns.csv

# Read csv file
Eng_01_df <- read_csv("data/01_Eng_columns.csv") 

# Create dictionary
Eng_01_dictionary <- create_informant(Eng_01_df) %>% 
  info_tabular(
    Description = "Dataset of English vocabulary data. It includes all participants.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>%
  info_columns(
    columns = "n_months",
    info = "The month of administration, where 1 means the participant contributed data the first month after they entered the study. The subsequent numbers refer to the month when they contributed data along the study.") %>%
  info_columns(
    columns = "baa_baa":"then",
    info = "Shows if a participant produces (1) or does not produce (0) the word.") %>%
  info_columns(
    columns = "eng_total_produced",
    info = "Estimated expressive voabulary size.") 

Eng_01_dictionary
```

```{r}
# Data dictionary for 01_Eng_columns.csv

# Read csv file
Fr_01_df <- read_csv("data/01_Fr_columns.csv") 

# Create dictionary
Fr_01_dictionary <- create_informant(Fr_01_df) %>% 
  info_tabular(
    Description = "Dataset of French vocabulary data. It includes all participants.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>%
  info_columns(
    columns = "n_months",
    info = "The month of administration, where 1 means the participant contributed data the first month after they entered the study. The subsequent numbers refer to the month when they contributed data along the study.") %>%
  info_columns(
    columns = "aie":"si",
    info = "Shows if a participant produces (1) or does not produce (0) the word.") %>%
  info_columns(
    columns = "fr_total_produced",
    info = "Estimated expressive voabulary size.") 

Fr_01_dictionary
```

```{r}
################# Datasets used for Script 03 ################# 
```

```{r}
# Data dictionary for 02_Eng_keepers.csv

# Read csv file
Eng_02_df <- read_csv("data/02_Eng_keepers.csv")

# Create dictionary
Eng_02_dictionary <- create_informant(Eng_02_df) %>% 
  info_tabular(
    Description = "Dataset of English vocabulary data. It includes only participants that met inclusion criteria.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>%
  info_columns(
    columns = "n_months",
    info = "The month of administration, where 1 means the participant contributed data the first month after they entered the study. The subsequent numbers refer to the month when they contributed data along the study.") %>%
  info_columns(
    columns = "baa_baa":"then",
    info = "Shows if a participant produces (1) or does not produce (0) the word.") %>%
  info_columns(
    columns = "eng_total_produced",
    info = "Estimated expressive voabulary size.") 

Eng_02_dictionary
```

```{r}
# Data dictionary for 02_Fr_keepers.csv

# Read csv file
Fr_02_df <- read_csv("data/02_Fr_keepers.csv")

# Create dictionary
Fr_02_dictionary <- create_informant(Fr_02_df) %>% 
  info_tabular(
    Description = "Dataset of French vocabulary data. It includes only participants that met inclusion criteria.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>%
  info_columns(
    columns = "n_months",
    info = "The month of administration, where 1 means the participant contributed data the first month after they entered the study. The subsequent numbers refer to the month when they contributed data along the study.") %>%
  info_columns(
    columns = "aie":"si",
    info = "Shows if a participant produces (1) or does not produce (0) the word.") %>%
  info_columns(
    columns = "fr_total_produced",
    info = "Estimated expressive voabulary size.") 

Fr_02_dictionary
```

```{r}
# Data dictionary for ws_te_list_full.csv

# Read csv file
TE_list <- read_csv("data/ws_te_list_full.csv") %>%
  # remove unnecessary columns
  select(-c(word_en, word_fr, one_to_many)) %>%
  rename(eng_item_num = en_item_num)

# Create dictionary
TE_list_dictionary <- create_informant(TE_list) %>% 
  info_tabular(
    Description = "Dataset of translation equivalents included in the English and French CDI.") %>%
  info_columns(
    columns = "eng_item_num",
    info = "Item ID in the English CDI.") %>%
  info_columns(
    columns = "fr_item_num",
    info = "Item ID in the French CDI.") %>%
  info_columns(
    columns = "te_id",
    info = "ID assigned to translation equivalent pair.")

TE_list_dictionary
```

```{r}
################# Datasets used for Script 04 ################# 
```

```{r}
# Data dictionary for 03_vocabulary_scores.csv

# Read csv file
vocabulary_scores_03_df <- read_csv("data/03_vocabulary_scores.csv") 

# Create dictionary
vocabulary_scores_03_dictionary <- create_informant(vocabulary_scores_03_df) %>% 
  info_tabular(
    Description = "Dataset includes vocabulary data for English, French, word, and concept vocabularies.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>%
  info_columns(
    columns = "n_months",
    info = "The month of administration, where 1 means the participant contributed data the first month after they entered the study. The subsequent numbers refer to the month when they contributed data along the study.") %>% 
  info_columns(
    columns = ends_with("_produced"),
    info = "Indicates the number of words produced in that vocabulary type by a participant in that month.") %>% 
  info_columns(
    columns = "num_datapts",
    info = "Number of data points submitted by each participant along the study.") %>% 
  info_columns(
    columns = "age",
    info = "Participant's age in months.") %>% 
  info_columns(
    columns = "starting_age",
    info = "Participant's age in months when they joined the study.") 

vocabulary_scores_03_dictionary
```

```{r}
################# Datasets used for Scripts 05 and 05.2 ################# 
```

```{r}
# Data dictionary for 04_analysis_step_1_coefficients.csv

# Read csv file
coefficients_04_df <- read_csv("data/04_analysis_step_1_coefficients.csv")

# Create dictionary
coefficients_04_dictionary <- create_informant(coefficients_04_df) %>% 
  info_tabular(
    Description = "Dataset includes midpoint, slope, and upper limit coefficients of the logistic curves fit to individual vocabulary data. It also includes AIC values for different types or curves.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>%
  info_columns(
    columns = "vocabulary_type_step1",
    info = "Specifices if the coefficients correspond to English, French, word, or concept vocabulary.") %>%
  info_columns(
    columns = "AIC_LL.3",
    info = "AIC value for three-parameter logistic curve.") %>%
  info_columns(
    columns = "AIC_Cubic",
    info = "AIC value for cubic curve.") %>%
  info_columns(
    columns = "AIC_Quad",
    info = "AIC value for quadratic curve.") %>%
  info_columns(
    columns = "AIC_Lin",
    info = "AIC value for linear equation.") 

coefficients_04_dictionary
```

```{r}
# Data dictionary for 04_analysis_step_1_dataset.csv

# Read csv file
vocabulary_scores_df <- read_csv("data/04_analysis_step_1_dataset.csv") 

# Create dictionary
vocabulary_scores_dictionary <- create_informant(vocabulary_scores_df) %>% 
  info_tabular(
    Description = "Dataset includes information to estimate the number of words a participant learned during the vocbaulary spurt.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>% 
  info_columns(
    columns = "n_months",
    info = "The month of administration, where 1 means the participant contributed data the first month after they entered the study. The subsequent numbers refer to the month when they contributed data along the study.") %>% 
  info_columns(
    columns = "age",
    info = "Participant's age in months.") %>% 
  info_columns(
    columns = "starting_age",
    info = "Participant's age in months when they joined the study.") %>% 
  info_columns(
    columns = "num_datapts",
    info = "Number of data points submitted by each participant along the study.") %>% 
   info_columns(
    columns = "vocabulary_score",
    info = "Number of words produced in that month for that vocabulary type.") %>% 
  info_columns(
    columns = "num_missing_datapts",
    info = "Number of missing data points by each participant in each vocabulary type.") %>% 
  info_columns(
    columns = "total",
    info = "Number of words that a participant could potentially produce in each vocabulary type.") 

vocabulary_scores_dictionary
```

```{r}
################# Datasets used for Script 05.1 ################# 
```

```{r}
# Data dictionary for 05_final_exposure_dataset.csv

# Read csv file
final_exposure_df <- read_csv("data/05_final_exposure_dataset.csv")

# Create dictionary
final_exposure_dictionary <- create_informant(final_exposure_df) %>% 
  info_tabular(
    Description = "Dataset includes information about participants' language exposure at the end of the study.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>% 
  info_columns(
    columns = "end_age",
    info = "Participant's age in months at which the current phage ended.") %>%
  info_columns(
    columns = "cumulative_exp_Eng",
    info = "Exposure to English that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>%
  info_columns(
    columns = "cumulative_exp_Fre",
    info = "Exposure to French that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>%
  info_columns(
    columns = "lang_status",
    info = "Specifies if a participant is bilingual, English-monolingual or French-monolingual.") %>%
  info_columns(
    columns = "dominant_lang",
    info = "Specifies a participant's dominant language.") %>%
  info_columns(
    columns = "exposure_balance",
    info = "Specifies a participant's language exposure balance, computed as the exposure to the non-dominant language.")

final_exposure_dictionary
```

```{r}
# Data dictionary for 05_final_vocabulary_scores_dataset.csv

# Read csv file
final_vocabulary_scores_df <- read_csv("data/05_final_vocabulary_scores_dataset.csv")

# Create dictionary
final_vocabulary_scores_dictionary <- create_informant(final_vocabulary_scores_df) %>% 
  info_tabular(
    Description = "Dataset includes vocabulary data for English, French, word, and concept vocabularies on the final month of the study.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>%
  info_columns(
    columns = "n_months",
    info = "The month of administration, where 1 means the participant contributed data the first month after they entered the study. The subsequent numbers refer to the month when they contributed data along the study.") %>% 
  info_columns(
    columns = "num_datapts",
    info = "Number of data points submitted by each participant along the study.") %>% 
  info_columns(
    columns = "age",
    info = "Participant's age in months.") %>% 
  info_columns(
    columns = "starting_age",
    info = "Participant's age in months when they joined the study.") %>% 
  info_columns(
    columns = "vocabulary_type_step1",
    info = "Specifices if the data correspond to English, French, word, or concept vocabulary.") %>% 
  info_columns(
    columns = "vocabulary_score",
    info = "Number of words produced in that month for that vocabulary type.") %>% 
  info_columns(
    columns = "num_missing_datapts",
    info = "Number of missing data points by each participant in each vocabulary type.") %>% 
  info_columns(
    columns = "total",
    info = "Number of words that a participant could potentially produce in each vocabulary type.")

final_vocabulary_scores_dictionary
```

```{r}
# Data dictionary for 05_words_at_spurt_distinct_dataset.csv

# Read csv file
words_at_spurt_distinct <- read_csv('data/05_words_at_spurt_distinct_dataset.csv')

# Create dictionary
words_at_spurt_distinct_dictionary <- create_informant(words_at_spurt_distinct) %>% 
  info_tabular(
    Description = "Dataset includes the estimated number of words learned by each participant during the vocabulary spurt in each vocabulary type.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>% 
  info_columns(
    columns = "vocabulary_type_step1",
    info = "Specifices if the data correspond to English, French, word, or concept vocabulary.") %>% 
  info_columns(
    columns = "words_learned",
    info = "Estimated number of words learned by a participant during the month-long period around the vocabulary spurt. It is expressed in decimals because it was prorated, as measures were not taken exactly one month apart.")

words_at_spurt_distinct_dictionary
```

```{r}
################# Datasets used for Script 05.3 ################# 
```

```{r}
# Data dictionary for 05.3_demographics_analysis_step_2_dataset.csv

# Read csv file
step2_full_df <- read_csv('data/05.3_demographics_analysis_step_2_dataset.csv')

# Create dictionary
step2_full_dictionary <- create_informant(step2_full_df) %>% 
  info_tabular(
    Description = "Dataset includes all the variables needed to run regression models controling for demographic charactersitics. Some columns share a name buthad different ending; columns that end in '_eng' correspond those values entered in the English CDI, those that en in '_fr' corresponde to the French CDI. Discrepencies between the two forms were corrected.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>% 
  info_columns(
    columns = "vocabulary_type_step1",
    info = "Specifices if the data correspond to English, French, word, or concept vocabulary.") %>% 
  info_columns(
    columns = "vocabulary_type_step2",
    info = "Specifices if the data correspond to single-language (English or French), word, or concept vocabulary.") %>% 
  info_columns(
    columns = "midpoint":"upper_limit",
    info = "Coefficient estimated by fitting a logistic curve to individual vocabulary data.") %>%
  info_columns(
    columns = "AIC_LL.3",
    info = "AIC value for three-parameter logistic curve.") %>%
  info_columns(
    columns = "AIC_Cubic",
    info = "AIC value for cubic curve.") %>%
  info_columns(
    columns = "AIC_Quad",
    info = "AIC value for quadratic curve.") %>%
  info_columns(
    columns = "AIC_Lin",
    info = "AIC value for linear equation.") %>%
  info_columns(
    columns = "cumulative_exp_Eng",
    info = "Exposure to English that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>%
  info_columns(
    columns = "cumulative_exp_Fre",
    info = "Exposure to French that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>% 
  info_columns(
    columns = "end_age",
    info = "Participant's age in months at which the current phage ended.") %>%
  info_columns(
    columns = "lang_status",
    info = "Specifies if a participant is bilingual, English-monolingual or French-monolingual.") %>%
  info_columns(
    columns = "dominant_lang",
    info = "Specifies a participant's dominant language.") %>%
  info_columns(
    columns = "exposure_balance",
    info = "Specifies a participant's language exposure balance, computed as the exposure to the non-dominant language.") %>% 
  info_columns(
    columns = "exposure_percent",
    info = "Exposure to the specified language expressed in percentage.") %>% 
  info_columns(
    columns = "n_months",
    info = "The month of administration, where 1 means the participant contributed data the first month after they entered the study. The subsequent numbers refer to the month when they contributed data along the study.") %>% 
  info_columns(
    columns = "num_datapts",
    info = "Number of data points submitted by each participant along the study.") %>% 
  info_columns(
    columns = "age",
    info = "Participant's age in months.") %>% 
  info_columns(
    columns = "starting_age",
    info = "Participant's age in months when they joined the study.") %>% 
  info_columns(
    columns = "vocabulary_score",
    info = "Number of words produced in that month for that vocabulary type.") %>% 
  info_columns(
    columns = "num_missing_datapts",
    info = "Number of missing data points by each participant in each vocabulary type.") %>% 
  info_columns(
    columns = "total",
    info = "Number of words that a participant could potentially produce in each vocabulary type.") %>% 
  info_columns(
    columns = "dominance",
    info = "Specifies if the language referred to is the participant-s dominant or non/dominant language.") %>% 
  info_columns(
    columns = "words_learned",
    info = "Estimated number of words learned by a participant during the month-long period around the vocabulary spurt. It is expressed in decimals because it was prorated, as measures were not taken exactly one month apart.") %>%
  info_columns(
    columns = "correct_sex",
    info = "Child sex corrected in case of discrepancies between forms.") %>%
  info_columns(
    columns = "correct_birth_order",
    info = "Birth order corrected in case of discrepancies between forms.") %>%
  info_columns(
    columns = "correct_mother_education",
    info = "Mother education in years corrected in case of discrepancies between forms.") %>%
  info_columns(
    columns = "correct_father_education",
    info = "Father education in years corrected in case of discrepancies between forms.") %>%
  info_columns(
    columns = "correct_ethnicity",
    info = "Ethnicity corrected in case of discrepancies between forms.") %>%
  info_columns(
    columns = "correct_income",
    info = "Family annual income reported as ranges corrected in case of discrepancies between forms.") %>%
  info_columns(
    columns = "parental_education",
    info = "Average for mother and father education.") %>%
  info_columns(
    columns = "income_range_average",
    info = "Midpoint (average) of the income ranges.") %>%
  info_columns(
    columns = "birth_order_categorical",
    info = "Participants divided in two groups based on birth order: first-borns and later-borns.") 

step2_full_dictionary
```

```{r}
################# Datasets used for Script 06 ################# 

# All the csv files used for the robustness checks have been used in previous scripts. "RC_" has been added to the original dataframe name (e.g., RC_vocabulary_scores_03_df is the same dataset as vocabulary_scores_03_df).
```

```{r}
################# Datasets used for Script 07 ################# 

# Most csv files used for the manuscript script have been used in previous scripts. Some csv files were read and assigned to a name different than the original dataframe name. These are the dataframes with different names:

# step1_df is the same as vocabulary_scores_df
```

```{r}
# Data dictionary for 05_analysis_step_2_dataset.csv

# Read csv file
step2_df <- read_csv('data/05_analysis_step_2_dataset.csv')

# Create dictionary
step2_dictionary <- create_informant(step2_df) %>% 
  info_tabular(
    Description = "Dataset includes all the vocabulary and language exposure information for the regression models.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>% 
  info_columns(
    columns = "vocabulary_type_step1",
    info = "Specifices if the data correspond to English, French, word, or concept vocabulary.") %>% 
  info_columns(
    columns = "vocabulary_type_step2",
    info = "Specifices if the data correspond to single-language (English or French), word, or concept vocabulary.") %>% 
  info_columns(
    columns = "midpoint":"upper_limit",
    info = "Coefficient estimated by fitting a logistic curve to individual vocabulary data.") %>%
  info_columns(
    columns = "AIC_LL.3",
    info = "AIC value for three-parameter logistic curve.") %>%
  info_columns(
    columns = "AIC_Cubic",
    info = "AIC value for cubic curve.") %>%
  info_columns(
    columns = "AIC_Quad",
    info = "AIC value for quadratic curve.") %>%
  info_columns(
    columns = "AIC_Lin",
    info = "AIC value for linear equation.") %>%
  info_columns(
    columns = "cumulative_exp_Eng",
    info = "Exposure to English that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>%
  info_columns(
    columns = "cumulative_exp_Fre",
    info = "Exposure to French that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>% 
  info_columns(
    columns = "end_age",
    info = "Participant's age in months at which the current phage ended.") %>%
  info_columns(
    columns = "lang_status",
    info = "Specifies if a participant is bilingual, English-monolingual or French-monolingual.") %>%
  info_columns(
    columns = "dominant_lang",
    info = "Specifies a participant's dominant language.") %>%
  info_columns(
    columns = "exposure_balance",
    info = "Specifies a participant's language exposure balance, computed as the exposure to the non-dominant language.") %>% 
  info_columns(
    columns = "exposure_percent",
    info = "Exposure to the specified language expressed in percentage.") %>% 
  info_columns(
    columns = "n_months",
    info = "The month of administration, where 1 means the participant contributed data the first month after they entered the study. The subsequent numbers refer to the month when they contributed data along the study.") %>% 
  info_columns(
    columns = "num_datapts",
    info = "Number of data points submitted by each participant along the study.") %>% 
  info_columns(
    columns = "age",
    info = "Participant's age in months.") %>% 
  info_columns(
    columns = "starting_age",
    info = "Participant's age in months when they joined the study.") %>% 
  info_columns(
    columns = "vocabulary_score",
    info = "Number of words produced in that month for that vocabulary type.") %>% 
  info_columns(
    columns = "num_missing_datapts",
    info = "Number of missing data points by each participant in each vocabulary type.") %>% 
  info_columns(
    columns = "total",
    info = "Number of words that a participant could potentially produce in each vocabulary type.") %>% 
  info_columns(
    columns = "dominance",
    info = "Specifies if the language referred to is the participant-s dominant or non/dominant language.") %>% 
  info_columns(
    columns = "words_learned",
    info = "Estimated number of words learned by a participant during the month-long period around the vocabulary spurt. It is expressed in decimals because it was prorated, as measures were not taken exactly one month apart.")

step2_dictionary
```

```{r}
# Data dictionary for 05.1_midpoint_identification.csv

### The same variables are included in 05.1_midpoint_identification_summary.csv

# Read csv file
midpoint_identification <- read_csv('data/05.1_midpoint_identification.csv')

# Create dictionary
midpoint_identification_dictionary <- create_informant(midpoint_identification) %>% 
  info_tabular(
    Description = "Dataset includes all the vocabulary and language exposure information for the comparisson between spurters and non/spurters.") %>%
  info_columns(
    columns = "study_id",
    info = "Unique participant identifier.") %>% 
  info_columns(
    columns = "vocabulary_type_step1",
    info = "Specifices if the data correspond to English, French, word, or concept vocabulary.") %>% 
  info_columns(
    columns = "midpoint":"upper_limit",
    info = "Coefficient estimated by fitting a logistic curve to individual vocabulary data.") %>%
  info_columns(
    columns = "AIC_LL.3",
    info = "AIC value for three-parameter logistic curve.") %>%
  info_columns(
    columns = "AIC_Cubic",
    info = "AIC value for cubic curve.") %>%
  info_columns(
    columns = "AIC_Quad",
    info = "AIC value for quadratic curve.") %>%
  info_columns(
    columns = "AIC_Lin",
    info = "AIC value for linear equation.") %>%
  info_columns(
    columns = "cumulative_exp_Eng",
    info = "Exposure to English that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>%
  info_columns(
    columns = "cumulative_exp_Fre",
    info = "Exposure to French that a participant has had from birth to the current phase. Percentage expressed in decimal.") %>% 
  info_columns(
    columns = "end_age",
    info = "Participant's age in months at which the current phage ended.") %>%
  info_columns(
    columns = "lang_status",
    info = "Specifies if a participant is bilingual, English-monolingual or French-monolingual.") %>%
  info_columns(
    columns = "dominant_lang",
    info = "Specifies a participant's dominant language.") %>%
  info_columns(
    columns = "n_months",
    info = "The month of administration, where 1 means the participant contributed data the first month after they entered the study. The subsequent numbers refer to the month when they contributed data along the study.") %>% 
  info_columns(
    columns = "num_datapts",
    info = "Number of data points submitted by each participant along the study.") %>% 
  info_columns(
    columns = "age",
    info = "Participant's age in months.") %>% 
  info_columns(
    columns = "starting_age",
    info = "Participant's age in months when they joined the study.") %>% 
  info_columns(
    columns = "vocabulary_score",
    info = "Number of words produced in that month for that vocabulary type.") %>% 
  info_columns(
    columns = "num_missing_datapts",
    info = "Number of missing data points by each participant in each vocabulary type.") %>% 
  info_columns(
    columns = "total",
    info = "Number of words that a participant could potentially produce in each vocabulary type.") %>% 
  info_columns(
    columns = "midp_identify",
    info = "Specifies if a vocabulary spurt (i.e., midpoint) was identified within the study's age range.") 
  
midpoint_identification_dictionary
```

